services:
  app:
    build: ./app
    container_name: django_app_prod
    ports:
      - "8000:8000"
    volumes:
      - ./app/static:/app/static
    env_file:
      - app/.env.prod
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:18.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql
    env_file:
      - app/.env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/static
    depends_on:
      - app
volumes:
  postgres_data_prod:

