services:
  app:
    build: ./app
    container_name: django_app_prod
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - app/.env.prod
    depends_on:
      - db
  db:
    image: postgres:18.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app:/app
    env_file:
      - app/.env.prod
  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - app
volumes:
  postgres_data:

